### ISSUE TITLE
It looks like the dll is missing for Windows

### ISSUE THREAD

**Issue by stalhandske** [dkrprasetya/simple-disk-utils#1]
The x86 and x86_64 folders are missing in the plugin folder. Got this error when trying to run in the editor on windows. 

DllNotFoundException: DiskUtilsWinAPI
SimpleDiskUtils.DiskUtils.CheckAvailableSpace (System.String drive) (at Assets/Plugins/DiskUtils.cs:106)
TestDiskUtils.PrintStorageStats (System.String drive) (at Assets/SimpleDiskUtils/Sample/TestDiskUtils.cs:52)
TestDiskUtils+<Tests>c__Iterator6.MoveNext () (at Assets/SimpleDiskUtils/Sample/TestDiskUtils.cs:86)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
TestDiskUtils:Update() (at Assets/SimpleDiskUtils/Sample/TestDiskUtils.cs:38)

Seems like a really nice little asset though. @dkrprasetya

**Comment by dkrprasetya** [comment]
Ouch I did not check twice that it was not included in the commit...
I bet it is caused by the silly default .gitignore of GitHub windows.

In the mean time, you could make it work my building the .dll by yourself from the solution inside the "Windows" folder. Compile it for both x86 and x86_64, then put it in the corresponding folder.

I wil check my project again tomorrow and get back to you after pushing the .dll.

Thank you very much stalhandske for the report!

**Comment by stalhandske** [comment]
You are welcome.

Luckily I won't be needing the .dll for Windows since I'm only building for iOS, but I wanted to file the issue.

Cheers, and once again nice job on the plugin.

**Comment by dkrprasetya** [comment]
Hi, it has been almost 2 months since this issue is posted... My bad.

I have pushed the missing .dlls. It should have work fine for Windows too now.

Thanks again for the report!
